import type { CanvasComponent } from "../types/canvas";

/**
 * COMPREHENSIVE SYSTEM DESIGN COMPONENTS LIBRARY
 * Organized by architectural layers for scalable distributed systems
 * Last reviewed: Solution Architect Review
 */

export const COMPONENTS: CanvasComponent[] = [
  // ========================================
  // FRONTEND LAYER
  // ========================================
  {
    id: "web-app",
    group: "Frontend",
    icon: "💻",
    label: "Web App",
    description: "Browser-based client",
    tags: ["browser", "client", "frontend", "spa", "pwa", "web application"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "Web App",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "framework",
        label: "Framework",
        type: "select",
        default: "React",
        options: ["React", "Vue", "Angular", "Svelte"],
      },
      { key: "instances", label: "Instances", type: "number", default: 3 },
      {
        key: "cdn",
        label: "CDN Enabled",
        type: "boolean",
        default: true,
      },
      {
        key: "ssl",
        label: "SSL Enabled",
        type: "boolean",
        default: true,
      },
      {
        key: "staticAssets",
        label: "Static Assets (GB)",
        type: "number",
        default: 50,
      },
      {
        key: "logic",
        label: "Component Logic (Pseudo Code)",
        type: "textarea",
        placeholder: "submit -> validate -> call API -> show response",
        default: "",
      },
    ],
  },
  {
    id: "mobile-app",
    group: "Frontend",
    icon: "📱",
    label: "Mobile App",
    description: "iOS/Android client",
    tags: [
      "ios",
      "android",
      "mobile",
      "app",
      "native",
      "react native",
      "flutter",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "Mobile App",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        default: "",
        placeholder: "A brief description",
      },
      {
        key: "stack",
        label: "Tech Stack",
        type: "select",
        default: "React Native",
        options: ["React Native", "Flutter", "Swift/Kotlin"],
      },
      {
        key: "pushNotifications",
        label: "Push Notifications",
        type: "boolean",
        default: true,
      },
      {
        key: "offlineSupport",
        label: "Offline Support",
        type: "boolean",
        default: true,
      },
      {
        key: "sessions",
        label: "Active Sessions (k)",
        type: "number",
        default: 10,
      },
    ],
  },
  {
    id: "desktop-app",
    group: "Frontend",
    icon: "🖥️",
    label: "Desktop App",
    description: "Native / Electron client",
    tags: ["desktop", "electron", "tauri", "native", "windows", "mac", "linux"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "Desktop App",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        default: "",
        placeholder: "A brief description",
      },
      {
        key: "runtime",
        label: "Runtime",
        type: "select",
        default: "Electron",
        options: ["Electron", "Tauri", "Native"],
      },
      {
        key: "autoUpdate",
        label: "Auto Update",
        type: "boolean",
        default: true,
      },
      {
        key: "bundledSizeMB",
        label: "Bundle Size (MB)",
        type: "number",
        default: 120,
      },
    ],
  },

  // Data Layer group
  {
    id: "database",
    group: "Data Layer",
    icon: "🗄️",
    label: "Database",
    description: "Relational/NoSQL data storage",
    tags: [
      "db",
      "rdbms",
      "nosql",
      "sql",
      "postgres",
      "mysql",
      "mongodb",
      "data",
      "storage",
      "persistence",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Database",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "type",
        label: "Database Type",
        type: "select",
        default: "RDBMS",
        options: ["RDBMS", "NoSQL", "NewSQL", "Time-Series", "Graph"],
      },
      {
        key: "engine",
        label: "Engine",
        type: "select",
        default: "postgresql",
        options: [
          "postgresql",
          "mysql",
          "mongodb",
          "cassandra",
          "dynamodb",
          "cockroachdb",
        ],
      },
      {
        key: "workload",
        label: "Workload Type",
        type: "select",
        default: "OLTP",
        options: ["OLTP", "OLAP", "Hybrid"],
      },
      {
        key: "storageGB",
        label: "Storage (GB)",
        type: "number",
        default: 100,
      },
      {
        key: "sharding",
        label: "Sharding Strategy",
        type: "select",
        default: "None",
        options: ["None", "Hash-based", "Range-based", "Geographic"],
      },
      {
        key: "shards",
        label: "Number of Shards",
        type: "number",
        default: 1,
      },
      {
        key: "replication",
        label: "Replication Factor",
        type: "number",
        default: 3,
      },
      {
        key: "replicationMode",
        label: "Replication Mode",
        type: "select",
        default: "Async",
        options: ["Sync", "Async", "Semi-Sync"],
      },
      {
        key: "multiAZ",
        label: "Multi-AZ",
        type: "boolean",
        default: true,
      },
      {
        key: "crossRegion",
        label: "Cross-Region Replication",
        type: "boolean",
        default: false,
      },
      {
        key: "backups",
        label: "Automatic Backups",
        type: "boolean",
        default: true,
      },
      {
        key: "pitr",
        label: "Point-in-Time Recovery",
        type: "boolean",
        default: true,
      },
      {
        key: "encryption",
        label: "Encryption at Rest",
        type: "boolean",
        default: true,
      },
      {
        key: "connectionPooling",
        label: "Connection Pooling",
        type: "boolean",
        default: true,
      },
      {
        key: "queryCache",
        label: "Query Cache Enabled",
        type: "boolean",
        default: true,
      },
      {
        key: "wal",
        label: "Write-Ahead Logging",
        type: "boolean",
        default: true,
      },
      {
        key: "rbac",
        label: "RBAC Enabled",
        type: "boolean",
        default: true,
      },
      {
        key: "auditLog",
        label: "Audit Trail",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "loadbalancer",
    group: "Networking",
    icon: "⚖️",
    label: "Load Balancer",
    description: "Traffic distribution & high availability",
    tags: [
      "lb",
      "alb",
      "nlb",
      "elb",
      "traffic",
      "distribution",
      "nginx",
      "haproxy",
      "layer 4",
      "layer 7",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Load Balancer",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "type",
        label: "Type",
        type: "select",
        default: "Layer 7 (Application)",
        options: ["Layer 4 (Network)", "Layer 7 (Application)", "Global"],
      },
      {
        key: "algorithm",
        label: "Algorithm",
        type: "select",
        default: "round-robin",
        options: [
          "round-robin",
          "least-connections",
          "ip-hash",
          "weighted-round-robin",
          "least-response-time",
        ],
      },
      {
        key: "sslTermination",
        label: "SSL/TLS Termination",
        type: "boolean",
        default: true,
      },
      {
        key: "stickiness",
        label: "Session Stickiness",
        type: "boolean",
        default: false,
      },
      {
        key: "healthCheck",
        label: "Health Check",
        type: "boolean",
        default: true,
      },
      {
        key: "healthCheckInterval",
        label: "Health Check Interval (s)",
        type: "number",
        default: 30,
      },
      {
        key: "multiAZ",
        label: "Multi-AZ",
        type: "boolean",
        default: true,
      },
      {
        key: "accessLogs",
        label: "Access Logs",
        type: "boolean",
        default: true,
      },
      {
        key: "connectionDraining",
        label: "Connection Draining",
        type: "boolean",
        default: true,
      },
      {
        key: "ddosProtection",
        label: "DDoS Protection",
        type: "boolean",
        default: true,
      },
      {
        key: "waf",
        label: "WAF Enabled",
        type: "boolean",
        default: false,
      },
    ],
  },
  {
    id: "cache",
    group: "Data Layer",
    icon: "⚡",
    label: "Cache",
    description: "In-memory fast data access",
    tags: [
      "redis",
      "memcached",
      "in-memory",
      "caching",
      "performance",
      "speed",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Cache",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "engine",
        label: "Engine",
        type: "select",
        default: "redis",
        options: ["redis", "memcached", "hazelcast", "aerospike"],
      },
      {
        key: "cacheStrategy",
        label: "Cache Strategy",
        type: "select",
        default: "write-through",
        options: ["write-through", "write-around", "write-back", "cache-aside"],
      },
      {
        key: "ttl",
        label: "TTL (seconds)",
        type: "number",
        default: 3600,
      },
      {
        key: "inMemory",
        label: "In Memory",
        type: "boolean",
        default: true,
      },
      {
        key: "eviction",
        label: "Eviction Policy",
        type: "select",
        default: "lru",
        options: [
          "lru",
          "lfu",
          "fifo",
          "mru",
          "random",
          "ttl-based",
          "volatile-lru",
        ],
      },
      {
        key: "replication",
        label: "Replication",
        type: "boolean",
        default: true,
      },
      {
        key: "clusterMode",
        label: "Cluster Mode",
        type: "boolean",
        default: false,
      },
      {
        key: "persistence",
        label: "Persistence (AOF/RDB)",
        type: "boolean",
        default: false,
      },
      {
        key: "encryption",
        label: "Encryption in Transit",
        type: "boolean",
        default: true,
      },
      {
        key: "maxMemoryGB",
        label: "Max Memory (GB)",
        type: "number",
        default: 16,
      },
    ],
  },
  {
    id: "webserver",
    group: "Compute",
    icon: "🌐",
    label: "Web Server",
    description: "HTTP requests",
    tags: ["http", "server", "nginx", "apache", "web", "requests"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Web Server",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      { key: "instances", label: "Instances", type: "number", default: 2 },
      { key: "autoscale", label: "Autoscale", type: "boolean", default: true },
      {
        key: "instanceType",
        label: "Instance Type",
        type: "select",
        default: "t3.medium",
        options: ["t3.small", "t3.medium", "t3.large"],
      },
      { key: "gzip", label: "Gzip", type: "boolean", default: true },
      {
        key: "connectionTimeout",
        label: "Connection Timeout (s)",
        type: "number",
        default: 30,
      },
    ],
  },
  {
    id: "message-broker",
    group: "Messaging",
    icon: "📨",
    label: "Message Broker",
    description: "Pub/Sub message broker",
    tags: ["kafka", "rabbitmq", "pubsub", "messaging", "broker", "queue", "mq"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Message Broker",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      { key: "partitions", label: "Partitions", type: "number", default: 6 },
      {
        key: "replication",
        label: "Replication Factor",
        type: "number",
        default: 3,
      },
      {
        key: "durable",
        label: "Durable (persist messages)",
        type: "boolean",
        default: true,
      },
      {
        key: "retention",
        label: "Retention (hours)",
        type: "number",
        default: 168,
      },
    ],
  },
  {
    id: "auth-service",
    group: "Services",
    icon: "🔐",
    label: "Auth Service",
    description: "Authentication & session management",
    tags: [
      "authentication",
      "authorization",
      "auth",
      "oauth",
      "jwt",
      "sso",
      "login",
      "security",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Auth Service",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      { key: "oauth", label: "OAuth Enabled", type: "boolean", default: true },
      {
        key: "sessions",
        label: "Session Store",
        type: "select",
        default: "redis",
        options: ["redis", "database", "none"],
      },
      {
        key: "tokenTTL",
        label: "Token TTL (minutes)",
        type: "number",
        default: 60,
      },
      { key: "mfa", label: "MFA Required", type: "boolean", default: false },
    ],
  },
  {
    id: "cdn",
    group: "Delivery",
    icon: "🚀",
    label: "CDN",
    description: "Content delivery network",
    tags: [
      "content delivery",
      "cloudflare",
      "akamai",
      "fastly",
      "edge",
      "caching",
      "cdn",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "CDN",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "provider",
        label: "Provider",
        type: "select",
        default: "Cloudflare",
        options: ["Cloudflare", "Akamai", "Fastly", "AWS CloudFront"],
      },
      {
        key: "ttl",
        label: "Edge TTL (seconds)",
        type: "number",
        default: 3600,
      },
      {
        key: "cacheInvalidation",
        label: "Cache Invalidation (manual)",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "search",
    group: "Services",
    icon: "🔎",
    label: "Search",
    description: "Search engine & indexing",
    tags: [
      "elasticsearch",
      "opensearch",
      "search engine",
      "indexing",
      "full-text",
      "lucene",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Search",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "engine",
        label: "Engine",
        type: "select",
        default: "elasticsearch",
        options: ["elasticsearch", "opensearch", "meilisearch"],
      },
      { key: "replicas", label: "Replicas", type: "number", default: 2 },
      {
        key: "indexing",
        label: "Real-time indexing",
        type: "boolean",
        default: true,
      },
      { key: "shards", label: "Shards", type: "number", default: 5 },
    ],
  },
  {
    id: "queue",
    group: "Messaging",
    icon: "📮",
    label: "Queue",
    description: "Task queue",
    tags: ["task queue", "job queue", "sqs", "celery", "worker queue", "async"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Queue",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "visibilityTimeout",
        label: "Visibility Timeout (seconds)",
        type: "number",
        default: 30,
      },
      { key: "maxRetries", label: "Max Retries", type: "number", default: 5 },
      {
        key: "durable",
        label: "Durable (persist tasks)",
        type: "boolean",
        default: true,
      },
      {
        key: "backoff",
        label: "Backoff Strategy",
        type: "select",
        default: "exponential",
        options: ["fixed", "linear", "exponential"],
      },
    ],
  },
  {
    id: "analytics",
    group: "Data Layer",
    icon: "📊",
    label: "Analytics",
    description: "Event analytics pipeline",
    tags: [
      "data analytics",
      "metrics",
      "events",
      "tracking",
      "bi",
      "business intelligence",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Analytics",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "retentionDays",
        label: "Retention (days)",
        type: "number",
        default: 90,
      },
      {
        key: "samplingRate",
        label: "Sampling Rate (%)",
        type: "number",
        default: 100,
      },
      {
        key: "realTime",
        label: "Real-time processing",
        type: "boolean",
        default: true,
      },
      {
        key: "storage",
        label: "Storage",
        type: "select",
        default: "s3",
        options: ["s3", "gcs", "azure_blob"],
      },
    ],
  },

  // DNS Resolution & Network Entry group
  {
    id: "root-nameserver",
    group: "DNS & Network",
    icon: "🌍",
    label: "Root Nameserver",
    description: "Top-level DNS resolver",
    tags: ["dns", "nameserver", "root", "resolver", "domain"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Root Nameserver",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "ttl",
        label: "TTL (seconds)",
        type: "number",
        default: 172800,
      },
      {
        key: "dnssec",
        label: "DNSSEC Enabled",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "tld-nameserver",
    group: "DNS & Network",
    icon: "🔗",
    label: "TLD Nameserver",
    description: "Top-level domain nameserver",
    tags: ["dns", "tld", "top-level domain", "nameserver", ".com", ".org"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "TLD Nameserver",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "tld",
        label: "TLD",
        type: "select",
        default: ".com",
        options: [".com", ".org", ".net", ".io", ".dev"],
      },
      {
        key: "ttl",
        label: "TTL (seconds)",
        type: "number",
        default: 86400,
      },
    ],
  },
  {
    id: "authoritative-nameserver",
    group: "DNS & Network",
    icon: "📡",
    label: "Authoritative Nameserver",
    description: "Domain-specific DNS server",
    tags: ["dns", "authoritative", "nameserver", "domain", "records"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Authoritative Nameserver",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "records",
        label: "DNS Records",
        type: "number",
        default: 100,
      },
      {
        key: "ttl",
        label: "TTL (seconds)",
        type: "number",
        default: 3600,
      },
      {
        key: "anycast",
        label: "Anycast Enabled",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "isp",
    group: "DNS & Network",
    icon: "🌐",
    label: "ISP",
    description: "Internet Service Provider",
    tags: ["internet", "isp", "network", "provider", "connectivity"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "ISP",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "dnsCache",
        label: "DNS Cache Enabled",
        type: "boolean",
        default: true,
      },
      {
        key: "bandwidth",
        label: "Bandwidth (Gbps)",
        type: "number",
        default: 10,
      },
    ],
  },

  // API Gateway
  {
    id: "api-gateway",
    group: "Networking",
    icon: "🚪",
    label: "API Gateway",
    description: "Central API entry point",
    tags: [
      "api",
      "gateway",
      "rest",
      "graphql",
      "entry point",
      "routing",
      "kong",
      "apigee",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "API Gateway",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "inputValidation",
        label: "Input Validation",
        type: "boolean",
        default: true,
      },
      {
        key: "authentication",
        label: "Authentication",
        type: "select",
        default: "OAuth 2.0",
        options: ["OAuth 2.0", "JWT", "API Key", "Basic Auth"],
      },
      {
        key: "rateLimiting",
        label: "Rate Limiting",
        type: "boolean",
        default: true,
      },
      {
        key: "requestsPerSecond",
        label: "Max Requests/Second",
        type: "number",
        default: 1000,
      },
      {
        key: "tlsTermination",
        label: "TLS Termination",
        type: "boolean",
        default: true,
      },
      {
        key: "deduplication",
        label: "Request Deduplication",
        type: "boolean",
        default: true,
      },
      {
        key: "throttling",
        label: "Throttling Enabled",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Message Dispatcher
  {
    id: "message-dispatcher",
    group: "Messaging",
    icon: "📤",
    label: "Message Dispatcher",
    description: "Message routing & distribution",
    tags: ["message", "dispatcher", "routing", "distribution", "pub/sub"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Message Dispatcher",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "topics",
        label: "Topics",
        type: "number",
        default: 10,
      },
      {
        key: "loadBalancing",
        label: "Load Balancing",
        type: "select",
        default: "round-robin",
        options: ["round-robin", "least-load", "hash-based"],
      },
      {
        key: "partitioning",
        label: "Partitioning Enabled",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Distributed Services
  {
    id: "id-generator",
    group: "Services",
    icon: "🔢",
    label: "ID Generator",
    description: "Distributed unique ID generation",
    tags: [
      "id",
      "uuid",
      "snowflake",
      "ulid",
      "unique",
      "generator",
      "distributed",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "ID Generator",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "algorithm",
        label: "Algorithm",
        type: "select",
        default: "Snowflake",
        options: ["Snowflake", "UUID", "ULID", "Auto-Increment"],
      },
      {
        key: "shardId",
        label: "Shard ID",
        type: "number",
        default: 1,
      },
      {
        key: "distributed",
        label: "Distributed",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "distributed-lock",
    group: "Services",
    icon: "🔒",
    label: "Distributed Lock",
    description: "Resource locking & coordination",
    tags: [
      "lock",
      "distributed",
      "coordination",
      "mutex",
      "redis",
      "etcd",
      "zookeeper",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Distributed Lock",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "backend",
        label: "Backend",
        type: "select",
        default: "Redis",
        options: ["Redis", "Etcd", "Zookeeper", "Chubby"],
      },
      {
        key: "ttl",
        label: "Lock TTL (seconds)",
        type: "number",
        default: 30,
      },
      {
        key: "fairness",
        label: "Fair Locking",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Storage
  {
    id: "cold-storage",
    group: "Data Layer",
    icon: "❄️",
    label: "Cold Storage",
    description: "Archive & backup storage",
    tags: [
      "archive",
      "backup",
      "glacier",
      "cold storage",
      "long-term",
      "s3 glacier",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Cold Storage",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "provider",
        label: "Provider",
        type: "select",
        default: "AWS Glacier",
        options: ["AWS Glacier", "Azure Archive", "GCP Coldline"],
      },
      {
        key: "retentionDays",
        label: "Retention (days)",
        type: "number",
        default: 2555,
      },
      {
        key: "encryption",
        label: "Encryption at Rest",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "object-storage",
    group: "Data Layer",
    icon: "🗃️",
    label: "Object Storage",
    description: "S3-compatible object store",
    tags: [
      "s3",
      "blob",
      "object storage",
      "aws s3",
      "azure blob",
      "gcs",
      "minio",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Object Storage",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "provider",
        label: "Provider",
        type: "select",
        default: "S3",
        options: ["S3", "Azure Blob", "GCS", "MinIO"],
      },
      {
        key: "versioning",
        label: "Versioning",
        type: "boolean",
        default: true,
      },
      {
        key: "checksumValidation",
        label: "Checksum Validation",
        type: "boolean",
        default: true,
      },
      {
        key: "storageGB",
        label: "Storage (GB)",
        type: "number",
        default: 1000,
      },
    ],
  },

  // Processing Workers
  {
    id: "processing-worker",
    group: "Compute",
    icon: "⚙️",
    label: "Processing Worker",
    description: "Background job processor",
    tags: [
      "worker",
      "background job",
      "async",
      "task processor",
      "celery",
      "sidekiq",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Processing Worker",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "tasks",
        label: "Task Types",
        type: "select",
        default: "Media Encoding",
        options: [
          "Media Encoding",
          "Thumbnail Generation",
          "Data Processing",
          "ML Inference",
        ],
      },
      {
        key: "concurrency",
        label: "Concurrent Jobs",
        type: "number",
        default: 10,
      },
      {
        key: "autoscale",
        label: "Auto-scale",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Common Services
  {
    id: "notification-service",
    group: "Services",
    icon: "🔔",
    label: "Notification Service",
    description: "Push notifications & alerts",
    tags: ["notification", "push", "email", "sms", "alerts", "fcm", "apns"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Notification Service",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "channels",
        label: "Channels",
        type: "select",
        default: "Push + Email",
        options: ["Push", "Email", "SMS", "Push + Email", "All"],
      },
      {
        key: "fanout",
        label: "Fan-out Support",
        type: "boolean",
        default: true,
      },
      {
        key: "batching",
        label: "Batch Notifications",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "recommendation-service",
    group: "Services",
    icon: "🎯",
    label: "Recommendation",
    description: "ML-based recommendations",
    tags: [
      "recommendation",
      "ml",
      "machine learning",
      "collaborative filtering",
      "personalization",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Recommendation",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "algorithm",
        label: "Algorithm",
        type: "select",
        default: "Collaborative Filtering",
        options: ["Collaborative Filtering", "Content-based", "Hybrid"],
      },
      {
        key: "realTime",
        label: "Real-time",
        type: "boolean",
        default: true,
      },
      {
        key: "cacheResults",
        label: "Cache Results",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "payment-service",
    group: "Services",
    icon: "💳",
    label: "Payment Service",
    description: "Payment processing & gateway",
    tags: [
      "payment",
      "stripe",
      "paypal",
      "transaction",
      "billing",
      "checkout",
      "pci",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Payment Service",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "gateway",
        label: "Gateway",
        type: "select",
        default: "Stripe",
        options: ["Stripe", "PayPal", "Braintree", "Square"],
      },
      {
        key: "pciDss",
        label: "PCI DSS Compliant",
        type: "boolean",
        default: true,
      },
      {
        key: "tokenization",
        label: "Card Tokenization",
        type: "boolean",
        default: true,
      },
      {
        key: "retry",
        label: "Auto-retry Failed",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "log-processing",
    group: "Services",
    icon: "📝",
    label: "Log Processing",
    description: "Log aggregation & analysis",
    tags: [
      "logging",
      "logs",
      "elk",
      "splunk",
      "aggregation",
      "analysis",
      "kibana",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Log Processing",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "pipeline",
        label: "Pipeline",
        type: "select",
        default: "ELK Stack",
        options: ["ELK Stack", "Splunk", "Datadog", "CloudWatch"],
      },
      {
        key: "retentionDays",
        label: "Retention (days)",
        type: "number",
        default: 30,
      },
      {
        key: "indexing",
        label: "Real-time Indexing",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "pubsub",
    group: "Messaging",
    icon: "📡",
    label: "Pub/Sub",
    description: "Publish-subscribe messaging",
    tags: [
      "pubsub",
      "publish",
      "subscribe",
      "messaging",
      "event",
      "google pubsub",
      "sns",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Pub/Sub",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "topics",
        label: "Topics",
        type: "number",
        default: 20,
      },
      {
        key: "fanout",
        label: "Fan-out Support",
        type: "boolean",
        default: true,
      },
      {
        key: "ordering",
        label: "Message Ordering",
        type: "boolean",
        default: false,
      },
      {
        key: "durable",
        label: "Durable Messages",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Frontend Server
  {
    id: "frontend-server",
    group: "Compute",
    icon: "🖥️",
    label: "Frontend Server",
    description: "Client-facing server",
    tags: ["frontend", "server", "websocket", "connection", "client-facing"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Frontend Server",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "inMemoryConnections",
        label: "In-Memory Connections",
        type: "boolean",
        default: true,
      },
      {
        key: "activeConnections",
        label: "Active Connections",
        type: "number",
        default: 10000,
      },
      {
        key: "websockets",
        label: "WebSocket Support",
        type: "boolean",
        default: true,
      },
      {
        key: "instances",
        label: "Instances",
        type: "number",
        default: 3,
      },
    ],
  },

  // Backend Server
  {
    id: "backend-server",
    group: "Compute",
    icon: "⚡",
    label: "Backend Server",
    description: "Application logic & microservices",
    tags: [
      "backend",
      "server",
      "microservices",
      "api",
      "business logic",
      "application",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Backend Server",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "architecture",
        label: "Architecture",
        type: "select",
        default: "Microservices",
        options: ["Monolith", "Microservices", "Serverless"],
      },
      {
        key: "instances",
        label: "Instances",
        type: "number",
        default: 5,
      },
      {
        key: "caching",
        label: "Caching Enabled",
        type: "boolean",
        default: true,
      },
      {
        key: "retry",
        label: "Retry Logic",
        type: "boolean",
        default: true,
      },
      {
        key: "bulkOps",
        label: "Bulk Operations",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Edge Server
  {
    id: "edge-server",
    group: "Delivery",
    icon: "🌍",
    label: "Edge Server",
    description: "Edge computing & caching",
    tags: ["edge", "edge computing", "edge network", "cdn", "streaming"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Edge Server",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "scope",
        label: "Scope",
        type: "select",
        default: "Regional",
        options: ["Global", "Regional", "Local"],
      },
      {
        key: "streaming",
        label: "Streaming Support",
        type: "boolean",
        default: true,
      },
      {
        key: "abr",
        label: "ABR (Adaptive Bitrate)",
        type: "boolean",
        default: true,
      },
      {
        key: "staticCache",
        label: "Static Cache",
        type: "boolean",
        default: true,
      },
    ],
  },

  // ========================================
  // MISSING CRITICAL COMPONENTS
  // ========================================

  // Service Mesh
  {
    id: "service-mesh",
    group: "Networking",
    icon: "🕸️",
    label: "Service Mesh",
    description: "Microservices communication layer",
    tags: [
      "service mesh",
      "istio",
      "linkerd",
      "consul",
      "mtls",
      "traffic management",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Service Mesh",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "provider",
        label: "Provider",
        type: "select",
        default: "Istio",
        options: ["Istio", "Linkerd", "Consul", "AWS App Mesh"],
      },
      {
        key: "mtls",
        label: "Mutual TLS",
        type: "boolean",
        default: true,
      },
      {
        key: "tracing",
        label: "Distributed Tracing",
        type: "boolean",
        default: true,
      },
      {
        key: "circuitBreaker",
        label: "Circuit Breaker",
        type: "boolean",
        default: true,
      },
      {
        key: "retryPolicy",
        label: "Retry Policy",
        type: "boolean",
        default: true,
      },
      {
        key: "trafficSplitting",
        label: "Traffic Splitting",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Container Orchestration
  {
    id: "container-orchestrator",
    group: "Compute",
    icon: "🐳",
    label: "Container Orchestrator",
    description: "Container management & orchestration",
    tags: [
      "kubernetes",
      "k8s",
      "docker",
      "container",
      "orchestration",
      "ecs",
      "pods",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "K8s Cluster",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        default: "Kubernetes",
        options: ["Kubernetes", "ECS", "Docker Swarm", "Nomad"],
      },
      {
        key: "nodes",
        label: "Worker Nodes",
        type: "number",
        default: 3,
      },
      {
        key: "autoscaling",
        label: "Auto-scaling (HPA)",
        type: "boolean",
        default: true,
      },
      {
        key: "ingress",
        label: "Ingress Controller",
        type: "boolean",
        default: true,
      },
      {
        key: "monitoring",
        label: "Monitoring (Prometheus)",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Serverless Function
  {
    id: "serverless-function",
    group: "Compute",
    icon: "λ",
    label: "Serverless Function",
    description: "Event-driven compute",
    tags: [
      "lambda",
      "serverless",
      "function app",
      "cloud function",
      "faas",
      "azure functions",
      "event-driven",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Lambda Function",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "runtime",
        label: "Runtime",
        type: "select",
        default: "Node.js",
        options: ["Node.js", "Python", "Java", "Go", ".NET", "Ruby"],
      },
      {
        key: "memoryMB",
        label: "Memory (MB)",
        type: "number",
        default: 512,
      },
      {
        key: "timeout",
        label: "Timeout (seconds)",
        type: "number",
        default: 30,
      },
      {
        key: "concurrency",
        label: "Concurrent Executions",
        type: "number",
        default: 100,
      },
      {
        key: "coldStart",
        label: "Cold Start Optimization",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Reverse Proxy
  {
    id: "reverse-proxy",
    group: "Networking",
    icon: "🔀",
    label: "Reverse Proxy",
    description: "Request routing & caching",
    tags: ["reverse proxy", "nginx", "haproxy", "envoy", "traefik", "proxy"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Reverse Proxy",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "server",
        label: "Server",
        type: "select",
        default: "Nginx",
        options: ["Nginx", "HAProxy", "Envoy", "Traefik"],
      },
      {
        key: "caching",
        label: "Response Caching",
        type: "boolean",
        default: true,
      },
      {
        key: "compression",
        label: "Compression (gzip/brotli)",
        type: "boolean",
        default: true,
      },
      {
        key: "ssl",
        label: "SSL/TLS",
        type: "boolean",
        default: true,
      },
      {
        key: "rateLimiting",
        label: "Rate Limiting",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Stream Processing
  {
    id: "stream-processor",
    group: "Data Layer",
    icon: "🌊",
    label: "Stream Processor",
    description: "Real-time data processing",
    tags: [
      "stream",
      "kafka streams",
      "flink",
      "spark streaming",
      "kinesis",
      "real-time",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Stream Processor",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "engine",
        label: "Engine",
        type: "select",
        default: "Kafka Streams",
        options: [
          "Kafka Streams",
          "Apache Flink",
          "Spark Streaming",
          "AWS Kinesis",
        ],
      },
      {
        key: "throughput",
        label: "Throughput (events/sec)",
        type: "number",
        default: 10000,
      },
      {
        key: "windowing",
        label: "Windowing Support",
        type: "boolean",
        default: true,
      },
      {
        key: "stateful",
        label: "Stateful Processing",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Data Warehouse
  {
    id: "data-warehouse",
    group: "Data Layer",
    icon: "🏭",
    label: "Data Warehouse",
    description: "OLAP & analytics storage",
    tags: [
      "data warehouse",
      "snowflake",
      "redshift",
      "bigquery",
      "olap",
      "analytics",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Data Warehouse",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        default: "Snowflake",
        options: ["Snowflake", "Redshift", "BigQuery", "Synapse"],
      },
      {
        key: "storageTB",
        label: "Storage (TB)",
        type: "number",
        default: 10,
      },
      {
        key: "compression",
        label: "Column Compression",
        type: "boolean",
        default: true,
      },
      {
        key: "partitioning",
        label: "Data Partitioning",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Monitoring & Observability
  {
    id: "monitoring",
    group: "Observability",
    icon: "📈",
    label: "Monitoring",
    description: "Metrics & alerting",
    tags: [
      "monitoring",
      "prometheus",
      "grafana",
      "datadog",
      "metrics",
      "alerts",
      "observability",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Monitoring",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "stack",
        label: "Stack",
        type: "select",
        default: "Prometheus + Grafana",
        options: ["Prometheus + Grafana", "Datadog", "New Relic", "CloudWatch"],
      },
      {
        key: "metrics",
        label: "Metrics Collection",
        type: "boolean",
        default: true,
      },
      {
        key: "alerts",
        label: "Alerting",
        type: "boolean",
        default: true,
      },
      {
        key: "retention",
        label: "Retention (days)",
        type: "number",
        default: 30,
      },
    ],
  },

  // Distributed Tracing
  {
    id: "tracing",
    group: "Observability",
    icon: "🔍",
    label: "Distributed Tracing",
    description: "Request flow tracking",
    tags: [
      "tracing",
      "jaeger",
      "zipkin",
      "distributed tracing",
      "apm",
      "x-ray",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Tracing",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        default: "Jaeger",
        options: ["Jaeger", "Zipkin", "AWS X-Ray", "Datadog APM"],
      },
      {
        key: "sampling",
        label: "Sampling Rate (%)",
        type: "number",
        default: 10,
      },
      {
        key: "retention",
        label: "Retention (days)",
        type: "number",
        default: 7,
      },
    ],
  },

  // Rate Limiter
  {
    id: "rate-limiter",
    group: "Services",
    icon: "🚦",
    label: "Rate Limiter",
    description: "Request throttling service",
    tags: ["rate limit", "throttling", "rate limiter", "token bucket", "quota"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Rate Limiter",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "algorithm",
        label: "Algorithm",
        type: "select",
        default: "Token Bucket",
        options: [
          "Token Bucket",
          "Leaky Bucket",
          "Fixed Window",
          "Sliding Window",
        ],
      },
      {
        key: "requestsPerMinute",
        label: "Requests/Minute",
        type: "number",
        default: 1000,
      },
      {
        key: "distributed",
        label: "Distributed",
        type: "boolean",
        default: true,
      },
      {
        key: "backend",
        label: "Backend",
        type: "select",
        default: "Redis",
        options: ["Redis", "In-Memory", "Database"],
      },
    ],
  },

  // Circuit Breaker
  {
    id: "circuit-breaker",
    group: "Services",
    icon: "⚡",
    label: "Circuit Breaker",
    description: "Fault tolerance & resilience",
    tags: [
      "circuit breaker",
      "fault tolerance",
      "resilience",
      "hystrix",
      "fallback",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Circuit Breaker",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "failureThreshold",
        label: "Failure Threshold (%)",
        type: "number",
        default: 50,
      },
      {
        key: "timeout",
        label: "Timeout (ms)",
        type: "number",
        default: 5000,
      },
      {
        key: "fallback",
        label: "Fallback Strategy",
        type: "boolean",
        default: true,
      },
    ],
  },

  // File Storage
  {
    id: "file-storage",
    group: "Data Layer",
    icon: "📂",
    label: "File Storage",
    description: "Shared file system",
    tags: ["file storage", "nfs", "efs", "shared storage", "file system"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "File Storage",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "type",
        label: "Type",
        type: "select",
        default: "NFS",
        options: ["NFS", "EFS", "Azure Files", "GCP Filestore"],
      },
      {
        key: "storageTB",
        label: "Storage (TB)",
        type: "number",
        default: 1,
      },
      {
        key: "throughput",
        label: "Throughput (MB/s)",
        type: "number",
        default: 100,
      },
    ],
  },

  // VPN Gateway
  {
    id: "vpn-gateway",
    group: "Networking",
    icon: "🔐",
    label: "VPN Gateway",
    description: "Secure network connection",
    tags: [
      "vpn",
      "gateway",
      "ipsec",
      "openvpn",
      "wireguard",
      "secure connection",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "VPN Gateway",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "protocol",
        label: "Protocol",
        type: "select",
        default: "IPSec",
        options: ["IPSec", "OpenVPN", "WireGuard"],
      },
      {
        key: "encryption",
        label: "Encryption",
        type: "select",
        default: "AES-256",
        options: ["AES-128", "AES-256", "ChaCha20"],
      },
      {
        key: "tunnels",
        label: "Active Tunnels",
        type: "number",
        default: 2,
      },
    ],
  },

  // Firewall
  {
    id: "firewall",
    group: "Security",
    icon: "🛡️",
    label: "Firewall",
    description: "Network security & filtering",
    tags: [
      "firewall",
      "waf",
      "security",
      "ips",
      "network firewall",
      "filtering",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Firewall",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "type",
        label: "Type",
        type: "select",
        default: "WAF",
        options: ["Network Firewall", "WAF", "Next-Gen Firewall"],
      },
      {
        key: "rules",
        label: "Active Rules",
        type: "number",
        default: 50,
      },
      {
        key: "ips",
        label: "IPS Enabled",
        type: "boolean",
        default: true,
      },
      {
        key: "logging",
        label: "Traffic Logging",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Secrets Manager
  {
    id: "secrets-manager",
    group: "Security",
    icon: "🔑",
    label: "Secrets Manager",
    description: "Credentials & secrets storage",
    tags: [
      "secrets",
      "vault",
      "credentials",
      "key management",
      "hashicorp vault",
      "secrets manager",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Secrets Manager",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "provider",
        label: "Provider",
        type: "select",
        default: "HashiCorp Vault",
        options: ["HashiCorp Vault", "AWS Secrets Manager", "Azure Key Vault"],
      },
      {
        key: "rotation",
        label: "Auto Rotation",
        type: "boolean",
        default: true,
      },
      {
        key: "encryption",
        label: "Encryption at Rest",
        type: "boolean",
        default: true,
      },
      {
        key: "audit",
        label: "Audit Logging",
        type: "boolean",
        default: true,
      },
    ],
  },

  // Email Service
  {
    id: "email-service",
    group: "Services",
    icon: "📧",
    label: "Email Service",
    description: "Transactional email delivery",
    tags: [
      "email",
      "sendgrid",
      "ses",
      "mailgun",
      "smtp",
      "transactional email",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Email Service",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "provider",
        label: "Provider",
        type: "select",
        default: "SendGrid",
        options: ["SendGrid", "AWS SES", "Mailgun", "Postmark"],
      },
      {
        key: "templates",
        label: "Template Support",
        type: "boolean",
        default: true,
      },
      {
        key: "tracking",
        label: "Open/Click Tracking",
        type: "boolean",
        default: true,
      },
      {
        key: "bounceHandling",
        label: "Bounce Handling",
        type: "boolean",
        default: true,
      },
    ],
  },

  // SMS Service
  {
    id: "sms-service",
    group: "Services",
    icon: "💬",
    label: "SMS Service",
    description: "SMS notifications & OTP",
    tags: ["sms", "twilio", "sns", "text message", "otp", "vonage"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "SMS Service",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "A brief description of the component",
        default: "",
      },
      {
        key: "provider",
        label: "Provider",
        type: "select",
        default: "Twilio",
        options: ["Twilio", "AWS SNS", "Vonage", "MessageBird"],
      },
      {
        key: "otp",
        label: "OTP Support",
        type: "boolean",
        default: true,
      },
      {
        key: "deliveryReports",
        label: "Delivery Reports",
        type: "boolean",
        default: true,
      },
    ],
  },

  // ========================================
  // CUSTOM COMPONENT
  // ========================================
  {
    id: "custom-component",
    group: "Custom",
    icon: "📦",
    label: "Custom Component",
    description: "Create your own custom component",
    tags: ["custom", "generic", "user-defined", "flexible", "other"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        placeholder: "Enter component name",
        default: "Custom Component",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Describe what this component does",
        default: "",
      },
      {
        key: "componentType",
        label: "Component Type",
        type: "text",
        placeholder: "e.g., Service, Database, Cache, etc.",
        default: "",
      },
      {
        key: "technology",
        label: "Technology/Tool",
        type: "text",
        placeholder: "e.g., Redis, Kafka, Custom API, etc.",
        default: "",
      },
      {
        key: "purpose",
        label: "Purpose",
        type: "textarea",
        placeholder: "What problem does this solve?",
        default: "",
      },
      {
        key: "notes",
        label: "Additional Notes",
        type: "textarea",
        placeholder: "Any additional details or configuration",
        default: "",
      },
    ],
  },

  // ========================================
  // AI & MACHINE LEARNING
  // ========================================
  {
    id: "ml-model",
    group: "AI & ML",
    icon: "🤖",
    label: "ML Model",
    description: "Machine Learning Model (inference/training)",
    tags: [
      "ml",
      "machine learning",
      "model",
      "ai",
      "inference",
      "training",
      "neural network",
    ],
    properties: [
      {
        key: "componentName",
        label: "Model Name",
        type: "text",
        default: "ML Model",
        placeholder: "Enter model name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Model description and purpose",
        default: "",
      },
      {
        key: "modelType",
        label: "Model Type",
        type: "select",
        default: "Classification",
        options: [
          "Classification",
          "Regression",
          "NLP",
          "Computer Vision",
          "Recommendation",
          "Forecasting",
          "Clustering",
          "Anomaly Detection",
        ],
      },
      {
        key: "framework",
        label: "Framework",
        type: "select",
        default: "TensorFlow",
        options: [
          "TensorFlow",
          "PyTorch",
          "Scikit-learn",
          "XGBoost",
          "Keras",
          "ONNX",
        ],
      },
      {
        key: "version",
        label: "Model Version",
        type: "text",
        placeholder: "e.g., v1.0",
        default: "v1.0",
      },
    ],
  },
  {
    id: "model-training",
    group: "AI & ML",
    icon: "🎓",
    label: "Model Training",
    description: "ML model training pipeline",
    tags: [
      "training",
      "ml",
      "pipeline",
      "learning",
      "dataset",
      "batch training",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "Model Training",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Training pipeline description",
        default: "",
      },
      {
        key: "computeType",
        label: "Compute Type",
        type: "select",
        default: "GPU",
        options: ["CPU", "GPU", "TPU", "Distributed"],
      },
      {
        key: "batchSize",
        label: "Batch Size",
        type: "number",
        default: 32,
      },
      {
        key: "epochs",
        label: "Epochs",
        type: "number",
        default: 100,
      },
    ],
  },
  {
    id: "model-serving",
    group: "AI & ML",
    icon: "🚀",
    label: "Model Serving",
    description: "ML model serving/inference API",
    tags: [
      "inference",
      "serving",
      "prediction",
      "api",
      "endpoint",
      "model deployment",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "Model Serving",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Model serving description",
        default: "",
      },
      {
        key: "platform",
        label: "Serving Platform",
        type: "select",
        default: "TensorFlow Serving",
        options: [
          "TensorFlow Serving",
          "TorchServe",
          "MLflow",
          "Seldon Core",
          "KServe",
          "Custom API",
        ],
      },
      {
        key: "instances",
        label: "Instances",
        type: "number",
        default: 3,
      },
      {
        key: "autoscaling",
        label: "Auto-scaling",
        type: "boolean",
        default: true,
      },
    ],
  },
  {
    id: "feature-store",
    group: "AI & ML",
    icon: "🗄️",
    label: "Feature Store",
    description: "Centralized feature storage for ML",
    tags: [
      "features",
      "ml",
      "data",
      "store",
      "feast",
      "feature engineering",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "Feature Store",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Feature store description",
        default: "",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        default: "Feast",
        options: ["Feast", "Tecton", "Hopsworks", "AWS SageMaker", "Custom"],
      },
      {
        key: "features",
        label: "Number of Features",
        type: "number",
        default: 100,
      },
    ],
  },
  {
    id: "data-labeling",
    group: "AI & ML",
    icon: "🏷️",
    label: "Data Labeling",
    description: "Data annotation and labeling service",
    tags: [
      "labeling",
      "annotation",
      "training data",
      "ground truth",
      "dataset",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "Data Labeling",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Labeling service description",
        default: "",
      },
      {
        key: "labelingType",
        label: "Labeling Type",
        type: "select",
        default: "Manual",
        options: ["Manual", "Semi-automated", "Active Learning", "Crowdsourced"],
      },
      {
        key: "dataType",
        label: "Data Type",
        type: "select",
        default: "Images",
        options: ["Images", "Text", "Audio", "Video", "Tabular"],
      },
    ],
  },
  {
    id: "mlops-pipeline",
    group: "AI & ML",
    icon: "⚙️",
    label: "MLOps Pipeline",
    description: "End-to-end ML operations pipeline",
    tags: [
      "mlops",
      "pipeline",
      "ci/cd",
      "automation",
      "deployment",
      "monitoring",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "MLOps Pipeline",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Pipeline description",
        default: "",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        default: "Kubeflow",
        options: [
          "Kubeflow",
          "MLflow",
          "AWS SageMaker",
          "Azure ML",
          "Vertex AI",
          "Custom",
        ],
      },
      {
        key: "stages",
        label: "Pipeline Stages",
        type: "text",
        placeholder: "e.g., train -> validate -> deploy",
        default: "train -> validate -> deploy",
      },
    ],
  },
  {
    id: "model-registry",
    group: "AI & ML",
    icon: "📚",
    label: "Model Registry",
    description: "Centralized model versioning and registry",
    tags: [
      "registry",
      "versioning",
      "models",
      "metadata",
      "tracking",
      "mlflow",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "Model Registry",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Registry description",
        default: "",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        default: "MLflow",
        options: ["MLflow", "AWS SageMaker", "Azure ML", "Vertex AI", "Custom"],
      },
      {
        key: "models",
        label: "Registered Models",
        type: "number",
        default: 10,
      },
    ],
  },
  {
    id: "vector-database",
    group: "AI & ML",
    icon: "🧮",
    label: "Vector Database",
    description: "Vector embeddings storage for similarity search",
    tags: [
      "vector",
      "embeddings",
      "similarity",
      "search",
      "rag",
      "retrieval",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "Vector Database",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Vector DB description",
        default: "",
      },
      {
        key: "engine",
        label: "Engine",
        type: "select",
        default: "Pinecone",
        options: [
          "Pinecone",
          "Weaviate",
          "Milvus",
          "Qdrant",
          "Chroma",
          "FAISS",
          "pgvector",
        ],
      },
      {
        key: "dimensions",
        label: "Vector Dimensions",
        type: "number",
        default: 768,
      },
      {
        key: "indexType",
        label: "Index Type",
        type: "select",
        default: "HNSW",
        options: ["HNSW", "IVF", "Flat", "LSH"],
      },
    ],
  },
  {
    id: "llm-api",
    group: "AI & ML",
    icon: "💬",
    label: "LLM API",
    description: "Large Language Model API endpoint",
    tags: ["llm", "gpt", "language model", "openai", "api", "chatbot", "ai"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "LLM API",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "LLM API description",
        default: "",
      },
      {
        key: "provider",
        label: "Provider",
        type: "select",
        default: "OpenAI",
        options: [
          "OpenAI",
          "Anthropic",
          "Google PaLM",
          "Azure OpenAI",
          "Hugging Face",
          "Self-hosted",
        ],
      },
      {
        key: "model",
        label: "Model",
        type: "text",
        placeholder: "e.g., gpt-4, claude-3",
        default: "gpt-4",
      },
      {
        key: "maxTokens",
        label: "Max Tokens",
        type: "number",
        default: 4096,
      },
    ],
  },
  {
    id: "gpu-cluster",
    group: "AI & ML",
    icon: "🖥️",
    label: "GPU Cluster",
    description: "GPU computing cluster for ML workloads",
    tags: ["gpu", "compute", "cluster", "training", "nvidia", "cuda"],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "GPU Cluster",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "GPU cluster description",
        default: "",
      },
      {
        key: "gpuType",
        label: "GPU Type",
        type: "select",
        default: "NVIDIA A100",
        options: [
          "NVIDIA A100",
          "NVIDIA V100",
          "NVIDIA T4",
          "NVIDIA H100",
          "AMD MI250",
        ],
      },
      {
        key: "nodes",
        label: "Number of Nodes",
        type: "number",
        default: 4,
      },
      {
        key: "gpusPerNode",
        label: "GPUs per Node",
        type: "number",
        default: 8,
      },
    ],
  },
  {
    id: "experiment-tracking",
    group: "AI & ML",
    icon: "📊",
    label: "Experiment Tracking",
    description: "ML experiment tracking and visualization",
    tags: [
      "experiments",
      "tracking",
      "metrics",
      "mlflow",
      "wandb",
      "monitoring",
    ],
    properties: [
      {
        key: "componentName",
        label: "Component Name",
        type: "text",
        default: "Experiment Tracking",
        placeholder: "Enter component name",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Experiment tracking description",
        default: "",
      },
      {
        key: "platform",
        label: "Platform",
        type: "select",
        default: "MLflow",
        options: [
          "MLflow",
          "Weights & Biases",
          "TensorBoard",
          "Neptune.ai",
          "Comet ML",
        ],
      },
      {
        key: "experiments",
        label: "Active Experiments",
        type: "number",
        default: 5,
      },
    ],
  },

  // ========================================
  // GROUPING / CLUSTERS
  // ========================================
  {
    id: "group-cluster",
    group: "Grouping",
    icon: "📦",
    label: "Cluster/Group",
    description: "Container for grouping multiple components",
    tags: ["group", "cluster", "container", "zone", "boundary", "region"],
    properties: [
      {
        key: "componentName",
        label: "Group Name",
        type: "text",
        placeholder: "e.g., Backend Cluster, Database Zone",
        default: "Cluster",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Purpose of this cluster/group",
        default: "",
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "text",
        placeholder: "e.g., rgba(100, 100, 255, 0.05)",
        default: "rgba(100, 100, 255, 0.05)",
      },
      {
        key: "borderColor",
        label: "Border Color",
        type: "text",
        placeholder: "e.g., rgba(100, 100, 255, 0.3)",
        default: "rgba(100, 100, 255, 0.3)",
      },
    ],
  },
  {
    id: "availability-zone",
    group: "Grouping",
    icon: "🌐",
    label: "Availability Zone",
    description: "Isolated location within a region",
    tags: ["az", "availability zone", "fault isolation", "zone", "region"],
    properties: [
      {
        key: "componentName",
        label: "Zone Name",
        type: "text",
        placeholder: "e.g., us-east-1a, AZ-1",
        default: "Availability Zone",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Zone details",
        default: "",
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "text",
        placeholder: "Zone background color",
        default: "rgba(34, 139, 34, 0.05)",
      },
      {
        key: "borderColor",
        label: "Border Color",
        type: "text",
        placeholder: "Zone border color",
        default: "rgba(34, 139, 34, 0.3)",
      },
    ],
  },
  {
    id: "vpc-network",
    group: "Grouping",
    icon: "🔒",
    label: "VPC/Network",
    description: "Virtual private cloud boundary",
    tags: ["vpc", "network", "subnet", "private", "isolated"],
    properties: [
      {
        key: "componentName",
        label: "VPC Name",
        type: "text",
        placeholder: "e.g., Production VPC",
        default: "VPC",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Network details",
        default: "",
      },
      {
        key: "cidr",
        label: "CIDR Block",
        type: "text",
        placeholder: "e.g., 10.0.0.0/16",
        default: "10.0.0.0/16",
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "text",
        placeholder: "VPC background color",
        default: "rgba(128, 0, 128, 0.05)",
      },
      {
        key: "borderColor",
        label: "Border Color",
        type: "text",
        placeholder: "VPC border color",
        default: "rgba(128, 0, 128, 0.3)",
      },
    ],
  },
  {
    id: "microservice-group",
    group: "Grouping",
    icon: "🎯",
    label: "Microservice Group",
    description: "Related microservices cluster",
    tags: ["microservices", "service group", "domain", "bounded context"],
    properties: [
      {
        key: "componentName",
        label: "Service Group",
        type: "text",
        placeholder: "e.g., User Services, Payment Domain",
        default: "Service Group",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Service group purpose",
        default: "",
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "text",
        placeholder: "Group background color",
        default: "rgba(255, 165, 0, 0.05)",
      },
      {
        key: "borderColor",
        label: "Border Color",
        type: "text",
        placeholder: "Group border color",
        default: "rgba(255, 165, 0, 0.3)",
      },
    ],
  },
  {
    id: "security-boundary",
    group: "Grouping",
    icon: "🛡️",
    label: "Security Boundary",
    description: "Security zone/perimeter",
    tags: ["security", "dmz", "firewall", "boundary", "zone"],
    properties: [
      {
        key: "componentName",
        label: "Security Zone",
        type: "text",
        placeholder: "e.g., DMZ, Internal, Restricted",
        default: "Security Boundary",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Security zone details",
        default: "",
      },
      {
        key: "level",
        label: "Security Level",
        type: "select",
        default: "Internal",
        options: ["Public", "DMZ", "Internal", "Restricted"],
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "text",
        placeholder: "Zone background color",
        default: "rgba(255, 0, 0, 0.05)",
      },
      {
        key: "borderColor",
        label: "Border Color",
        type: "text",
        placeholder: "Zone border color",
        default: "rgba(255, 0, 0, 0.3)",
      },
    ],
  },
  {
    id: "custom-group",
    group: "Grouping",
    icon: "📦",
    label: "Custom Group",
    description: "Create your own custom group/container",
    tags: [
      "custom",
      "group",
      "container",
      "user-defined",
      "flexible",
      "boundary",
    ],
    properties: [
      {
        key: "componentName",
        label: "Group Name",
        type: "text",
        placeholder: "Enter custom group name",
        default: "Custom Group",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Describe the purpose of this group",
        default: "",
      },
      {
        key: "groupType",
        label: "Group Type",
        type: "text",
        placeholder: "e.g., Region, Data Center, Team, etc.",
        default: "",
      },
      {
        key: "icon",
        label: "Icon",
        type: "text",
        placeholder: "e.g., 🎨, 🏢, 🌍, etc.",
        default: "📦",
      },
      {
        key: "backgroundColor",
        label: "Background Color",
        type: "text",
        placeholder: "e.g., rgba(100, 100, 255, 0.05)",
        default: "rgba(100, 100, 255, 0.05)",
      },
      {
        key: "borderColor",
        label: "Border Color",
        type: "text",
        placeholder: "e.g., rgba(100, 100, 255, 0.3)",
        default: "rgba(100, 100, 255, 0.3)",
      },
      {
        key: "subtitle",
        label: "Subtitle",
        type: "text",
        placeholder: "Optional subtitle text",
        default: "",
      },
      {
        key: "notes",
        label: "Additional Notes",
        type: "textarea",
        placeholder: "Any additional details",
        default: "",
      },
    ],
  },

  // ========================================
  // ENTITY-RELATIONSHIP DIAGRAM (ERD)
  // ========================================
  {
    id: "entity",
    group: "ER Diagram",
    icon: "📋",
    label: "Entity",
    description: "Database table/entity with attributes",
    nodeType: "tableNode",
    tags: ["entity", "table", "database", "erd", "relation", "schema", "model"],
    properties: [
      {
        key: "componentName",
        label: "Entity Name",
        type: "text",
        placeholder: "e.g., User, Order, Product",
        default: "Entity",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Describe what this entity represents",
        default: "",
      },
      {
        key: "tableType",
        label: "Table Type",
        type: "select",
        default: "Regular",
        options: ["Regular", "Junction", "Audit", "Archive", "View", "Materialized View"],
      },
    ],
    data: {
      attributes: [
        { id: "attr-1", name: "id", type: "UUID", isPrimaryKey: true, isNullable: false },
        { id: "attr-2", name: "name", type: "VARCHAR(100)", isNullable: false },
        { id: "attr-3", name: "created_at", type: "TIMESTAMP", isNullable: false },
      ],
    },
    renderConfig: {
      shape: "table",
      sections: [
        { type: "header", editable: false },
        { type: "attributes", editable: true },
      ],
      columns: [
        { 
          key: "isPrimaryKey", 
          label: "PK", 
          width: "w-6", 
          type: "boolean",
          icon: { active: "🔑", inactive: "" },
          color: { active: "text-yellow-600 dark:text-yellow-400", inactive: "text-gray-400" }
        },
        { 
          key: "name", 
          label: "Column Name", 
          width: "flex-1", 
          type: "text",
          editable: true,
          color: { active: "font-semibold" }
        },
        { 
          key: "type", 
          label: "Data Type", 
          width: "w-24", 
          type: "text",
          editable: true
        },
        { 
          key: "isForeignKey", 
          label: "FK", 
          width: "w-6", 
          type: "boolean",
          icon: { active: "🔗", inactive: "" },
          color: { active: "text-blue-600 dark:text-blue-400", inactive: "text-gray-400" }
        },
        { 
          key: "isUnique", 
          label: "UQ", 
          width: "w-6", 
          type: "boolean",
          icon: { active: "★", inactive: "" },
          color: { active: "text-purple-600 dark:text-purple-400", inactive: "text-gray-400" }
        },
        { 
          key: "isNullable", 
          label: "NULL", 
          width: "w-8", 
          type: "boolean",
          icon: { active: "✓", inactive: "✗" },
          color: { active: "text-gray-400", inactive: "text-red-600 dark:text-red-400" }
        },
        { 
          key: "actions", 
          label: "", 
          width: "w-8", 
          type: "readonly"
        },
      ],
    },
  },
  {
    id: "weak-entity",
    group: "ER Diagram",
    icon: "📄",
    label: "Weak Entity",
    description: "Entity dependent on another entity for identification",
    nodeType: "tableNode",
    tags: ["weak entity", "dependent", "erd", "relationship", "partial key"],
    properties: [
      {
        key: "componentName",
        label: "Entity Name",
        type: "text",
        placeholder: "e.g., OrderItem, Dependent, Comment",
        default: "Weak Entity",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Describe this weak entity",
        default: "",
      },
      {
        key: "ownerEntity",
        label: "Owner Entity",
        type: "text",
        placeholder: "Parent entity that this depends on",
        default: "",
      },
      {
        key: "tableType",
        label: "Table Type",
        type: "select",
        default: "Weak Entity",
        options: ["Weak Entity", "Junction", "Dependent"],
      },
    ],
    data: {
      attributes: [
        { id: "attr-1", name: "owner_id", type: "UUID", isForeignKey: true, isNullable: false },
        { id: "attr-2", name: "sequence_number", type: "INT", isPrimaryKey: true, isNullable: false },
        { id: "attr-3", name: "data", type: "VARCHAR(255)", isNullable: false },
      ],
    },
    renderConfig: {
      shape: "table",
      sections: [
        { type: "header", editable: false },
        { type: "attributes", editable: true },
      ],
      columns: [
        { 
          key: "isPrimaryKey", 
          label: "PK", 
          width: "w-6", 
          type: "boolean",
          icon: { active: "🔑", inactive: "" },
          color: { active: "text-yellow-600 dark:text-yellow-400", inactive: "text-gray-400" }
        },
        { 
          key: "name", 
          label: "Column Name", 
          width: "flex-1", 
          type: "text",
          editable: true,
          color: { active: "font-semibold" }
        },
        { 
          key: "type", 
          label: "Data Type", 
          width: "w-24", 
          type: "text",
          editable: true
        },
        { 
          key: "isForeignKey", 
          label: "FK", 
          width: "w-6", 
          type: "boolean",
          icon: { active: "🔗", inactive: "" },
          color: { active: "text-blue-600 dark:text-blue-400", inactive: "text-gray-400" }
        },
        { 
          key: "isUnique", 
          label: "UQ", 
          width: "w-6", 
          type: "boolean",
          icon: { active: "★", inactive: "" },
          color: { active: "text-purple-600 dark:text-purple-400", inactive: "text-gray-400" }
        },
        { 
          key: "isNullable", 
          label: "NULL", 
          width: "w-8", 
          type: "boolean",
          icon: { active: "✓", inactive: "✗" },
          color: { active: "text-gray-400", inactive: "text-red-600 dark:text-red-400" }
        },
        { 
          key: "actions", 
          label: "", 
          width: "w-8", 
          type: "readonly"
        },
      ],
      borderStyle: "double",
      borderWidth: 4,
    },
  },
  {
    id: "er-trigger",
    group: "ER Diagram",
    nodeType: "erNode",
    icon: "⚡",
    label: "Trigger",
    description: "Database trigger for automated actions on events",
    tags: ["trigger", "automation", "event", "database", "erd"],
    properties: [
      {
        key: "nodeType",
        label: "Node Type",
        type: "text",
        default: "er-trigger",
      },
      {
        key: "componentName",
        label: "Trigger Name",
        type: "text",
        placeholder: "e.g., update_timestamp, log_changes, validate_data",
        default: "update_timestamp",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Describe what this trigger does",
        default: "Automatically updates the updated_at timestamp when a row is modified",
      },
      {
        key: "targetTable",
        label: "Target Table",
        type: "text",
        placeholder: "Table this trigger is attached to",
        default: "users",
      },
      {
        key: "timing",
        label: "Timing",
        type: "select",
        default: "BEFORE",
        options: ["BEFORE", "AFTER", "INSTEAD OF"],
      },
      {
        key: "event",
        label: "Event",
        type: "select",
        default: "UPDATE",
        options: ["INSERT", "UPDATE", "DELETE", "TRUNCATE"],
      },
      {
        key: "level",
        label: "Level",
        type: "select",
        default: "ROW",
        options: ["ROW", "STATEMENT"],
      },
      {
        key: "condition",
        label: "Condition (WHEN)",
        type: "textarea",
        placeholder: "Optional condition: e.g., NEW.status != OLD.status",
        default: "",
      },
    ],
    renderConfig: {
      shape: "note",
      sections: [
        { type: "header", editable: false },
        { type: "content", editable: false },
      ],
      minWidth: 200,
      minHeight: 100,
    },
  },
  {
    id: "er-note",
    group: "ER Diagram",
    nodeType: "erNode",
    icon: "📝",
    label: "Note/Constraint",
    description: "Business rule, constraint, or annotation",
    tags: ["note", "constraint", "rule", "annotation", "comment", "documentation"],
    properties: [
      {
        key: "nodeType",
        label: "Node Type",
        type: "text",
        default: "er-note",
      },
      {
        key: "componentName",
        label: "Note Title",
        type: "text",
        placeholder: "e.g., Business Rule, Constraint, Assumption",
        default: "Business Rule",
      },
      {
        key: "description",
        label: "Note Content",
        type: "textarea",
        placeholder: "Describe the rule, constraint, or important note\ne.g., Email must be unique across all users\nOrders can only be placed by verified customers",
        default: "Email addresses must be unique across all user accounts",
      },
      {
        key: "type",
        label: "Type",
        type: "select",
        default: "Business Rule",
        options: [
          "Business Rule",
          "Database Constraint",
          "Assumption",
          "Clarification",
          "TODO",
          "Warning",
          "Best Practice",
        ],
      },
      {
        key: "severity",
        label: "Severity",
        type: "select",
        default: "Info",
        options: ["Critical", "High", "Medium", "Low", "Info"],
      },
      {
        key: "relatedEntity",
        label: "Related To",
        type: "text",
        placeholder: "Entity or relationship this applies to",
        default: "",
      },
      {
        key: "sqlConstraint",
        label: "SQL Constraint",
        type: "textarea",
        placeholder: "SQL code for this constraint\ne.g., CHECK (price > 0)\nCHECK (start_date < end_date)",
        default: "",
      },
    ],
    renderConfig: {
      shape: "note",
      sections: [
        { type: "header", editable: false },
        { type: "content", editable: false },
      ],
      minWidth: 200,
      minHeight: 120,
      borderStyle: "dashed",
    },
  },
  {
    id: "er-view",
    group: "ER Diagram",
    nodeType: "tableNode",
    icon: "👁️",
    label: "View",
    description: "Database view or materialized view",
    tags: ["view", "query", "virtual table", "materialized", "aggregation"],
    properties: [
      {
        key: "componentName",
        label: "View Name",
        type: "text",
        placeholder: "e.g., active_users_view, order_summary_view",
        default: "View",
      },
      {
        key: "description",
        label: "Description",
        type: "textarea",
        placeholder: "Describe what this view provides",
        default: "",
      },
      {
        key: "viewType",
        label: "View Type",
        type: "select",
        default: "Standard View",
        options: ["Standard View", "Materialized View", "Indexed View", "Updateable View"],
      },
      {
        key: "baseTables",
        label: "Base Tables",
        type: "text",
        placeholder: "Tables this view depends on (comma-separated)",
        default: "",
      },
      {
        key: "tableType",
        label: "Table Type",
        type: "select",
        default: "View",
        options: ["View", "Materialized View", "Indexed View"],
      },
    ],
    data: {
      attributes: [
        { id: "attr-1", name: "id", type: "UUID", isPrimaryKey: false, isNullable: false },
        { id: "attr-2", name: "computed_field", type: "VARCHAR(100)", isNullable: true },
        { id: "attr-3", name: "aggregate_value", type: "INT", isNullable: true },
      ],
    },
    renderConfig: {
      shape: "table",
      sections: [
        { type: "header", editable: false },
        { type: "attributes", editable: true },
      ],
      columns: [
        { 
          key: "isPrimaryKey", 
          label: "PK", 
          width: "w-6", 
          type: "boolean",
          icon: { active: "🔑", inactive: "" },
          color: { active: "text-yellow-600 dark:text-yellow-400", inactive: "text-gray-400" }
        },
        { 
          key: "name", 
          label: "Column Name", 
          width: "flex-1", 
          type: "text",
          editable: true,
          color: { active: "font-semibold" }
        },
        { 
          key: "type", 
          label: "Data Type", 
          width: "w-24", 
          type: "text",
          editable: true
        },
        { 
          key: "isForeignKey", 
          label: "FK", 
          width: "w-6", 
          type: "boolean",
          icon: { active: "🔗", inactive: "" },
          color: { active: "text-blue-600 dark:text-blue-400", inactive: "text-gray-400" }
        },
        { 
          key: "isUnique", 
          label: "UQ", 
          width: "w-6", 
          type: "boolean",
          icon: { active: "★", inactive: "" },
          color: { active: "text-purple-600 dark:text-purple-400", inactive: "text-gray-400" }
        },
        { 
          key: "isNullable", 
          label: "NULL", 
          width: "w-8", 
          type: "boolean",
          icon: { active: "✓", inactive: "✗" },
          color: { active: "text-gray-400", inactive: "text-red-600 dark:text-red-400" }
        },
        { 
          key: "actions", 
          label: "", 
          width: "w-8", 
          type: "readonly"
        },
      ],
      borderStyle: "dashed",
      borderWidth: 1,
    },
  },
];


